# Triangular, pentagonal, and hexagonal
# Problem 45

# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

import time

start = time.time()

result = 0

def series(base):
    step_delta = base - 2
    step = 1
    n = 1
    yield n
    while True:
        step += step_delta
        n += step
        yield n

def is_pentagonal(x):
    if x < 1: return False
    n = round((1+(1+24*x)**0.5)/6)
    return n * (3*n - 1) == 2*x

def is_triangle(x):
    if x < 1: return False
    n = round((-1+(1+8*x)**0.5)/2)
    return n * (n + 1) == 2*x

      
for x in series(6):
    if x > 40755:
        if is_pentagonal(x) and is_triangle(x):
            result = x
            break

print('Result is {}'.format(result))

end = time.time()
print ('Time taken: {:.6f}s'.format(end - start))
